"""Initial schema

Revision ID: ec7a574b41b1
Revises: 
Create Date: 2026-09-18 22:24:09.232096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec7a574b41b1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('progress_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_progress_categories')),
    sa.UniqueConstraint('name', name=op.f('uq_progress_categories_name'))
    )
    with op.batch_alter_table('progress_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_progress_categories_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_progress_categories_slug'), ['slug'], unique=True)

    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('building', sa.String(length=60), nullable=False),
    sa.Column('floor', sa.Integer(), nullable=False),
    sa.Column('room_number', sa.String(length=30), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('room_type', sa.String(length=40), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('capacity > 0', name=op.f('ck_rooms_capacity_positive')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rooms')),
    sa.UniqueConstraint('building', 'room_number', name='uq_rooms_building_room_number')
    )
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rooms_building'), ['building'], unique=False)
        batch_op.create_index(batch_op.f('ix_rooms_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_rooms_room_number'), ['room_number'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('phone', sa.String(length=25), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'PARENT', 'STUDENT', name='user_role', native_enum=False), nullable=False),
    sa.Column('account_status', sa.Enum('PENDING_VERIFICATION', 'ACTIVE', 'BLOCKED', 'REJECTED', 'INACTIVE', name='account_status', native_enum=False), nullable=False),
    sa.Column('profile_photo', sa.String(length=255), nullable=True),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False),
    sa.Column('is_super_admin', sa.Boolean(), nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_account_status'), ['account_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_phone'), ['phone'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('admin_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('designation', sa.String(length=100), nullable=True),
    sa.Column('hostel_name', sa.String(length=150), nullable=True),
    sa.Column('notify_email', sa.Boolean(), nullable=False),
    sa.Column('notify_health_alerts', sa.Boolean(), nullable=False),
    sa.Column('notify_new_registrations', sa.Boolean(), nullable=False),
    sa.Column('notify_suggestions', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_admin_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin_profiles')),
    sa.UniqueConstraint('user_id', name=op.f('uq_admin_profiles_user_id'))
    )
    with op.batch_alter_table('admin_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_profiles_created_at'), ['created_at'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('admin_name', sa.String(length=150), nullable=True),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('affected_user_id', sa.Integer(), nullable=True),
    sa.Column('affected_user_name', sa.String(length=150), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], name=op.f('fk_audit_logs_admin_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['affected_user_id'], ['users.id'], name=op.f('fk_audit_logs_affected_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_admin_id'), ['admin_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_type'), ['entity_type'], unique=False)

    op.create_table('beds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('bed_number', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('fk_beds_room_id_rooms'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_beds')),
    sa.UniqueConstraint('room_id', 'bed_number', name='uq_beds_room_id_bed_number')
    )
    with op.batch_alter_table('beds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_beds_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_beds_room_id'), ['room_id'], unique=False)

    op.create_table('meals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('meal_type', sa.Enum('BREAKFAST', 'LUNCH', 'EVENING_SNACK', 'DINNER', name='meal_type', native_enum=False), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('food_items', sa.Text(), nullable=True),
    sa.Column('served_at', sa.Time(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_meals_created_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meals')),
    sa.UniqueConstraint('date', 'meal_type', name='uq_meals_date_meal_type')
    )
    with op.batch_alter_table('meals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meals_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_meals_date'), ['date'], unique=False)

    op.create_table('parents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=80), nullable=True),
    sa.Column('relationship_to_student', sa.String(length=50), nullable=True),
    sa.Column('occupation', sa.String(length=100), nullable=True),
    sa.Column('alternate_phone', sa.String(length=25), nullable=True),
    sa.Column('identity_document', sa.String(length=255), nullable=True),
    sa.Column('claimed_student_code', sa.String(length=50), nullable=True),
    sa.Column('verification_status', sa.Enum('PENDING', 'VERIFIED', 'REJECTED', name='parent_verification_status', native_enum=False), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('verified_by_id', sa.Integer(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('notify_email', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_parents_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by_id'], ['users.id'], name=op.f('fk_parents_verified_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_parents')),
    sa.UniqueConstraint('user_id', name=op.f('uq_parents_user_id'))
    )
    with op.batch_alter_table('parents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parents_claimed_student_code'), ['claimed_student_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_parents_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_parents_verification_status'), ['verification_status'], unique=False)

    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('requested_ip', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_password_reset_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_password_reset_tokens'))
    )
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('token_blocklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('token_type', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_token_blocklist_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_token_blocklist'))
    )
    with op.batch_alter_table('token_blocklist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_token_blocklist_jti'), ['jti'], unique=True)
        batch_op.create_index(batch_op.f('ix_token_blocklist_user_id'), ['user_id'], unique=False)

    op.create_table('meal_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meal_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('caption', sa.String(length=255), nullable=True),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['meal_id'], ['meals.id'], name=op.f('fk_meal_photos_meal_id_meals'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], name=op.f('fk_meal_photos_uploaded_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meal_photos'))
    )
    with op.batch_alter_table('meal_photos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meal_photos_meal_id'), ['meal_id'], unique=False)

    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('student_code', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', name='student_gender', native_enum=False), nullable=True),
    sa.Column('blood_group', sa.String(length=10), nullable=True),
    sa.Column('student_class', sa.String(length=40), nullable=True),
    sa.Column('section', sa.String(length=20), nullable=True),
    sa.Column('school_name', sa.String(length=150), nullable=True),
    sa.Column('phone', sa.String(length=25), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('admission_date', sa.Date(), nullable=True),
    sa.Column('profile_photo', sa.String(length=255), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=150), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=25), nullable=True),
    sa.Column('emergency_contact_relation', sa.String(length=50), nullable=True),
    sa.Column('bed_id', sa.Integer(), nullable=True),
    sa.Column('verification_status', sa.Enum('PENDING', 'VERIFIED', 'REJECTED', name='student_verification_status', native_enum=False), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('verified_by_id', sa.Integer(), nullable=True),
    sa.Column('current_status', sa.Enum('IN_HOSTEL', 'AT_SCHOOL', 'OUTSIDE_WITH_PERMISSION', 'ON_LEAVE', 'MEDICAL_FACILITY', 'RETURNED_TO_HOSTEL', name='student_current_status', native_enum=False), nullable=False),
    sa.Column('status_updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bed_id'], ['beds.id'], name=op.f('fk_students_bed_id_beds'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_students_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['verified_by_id'], ['users.id'], name=op.f('fk_students_verified_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_students')),
    sa.UniqueConstraint('bed_id', name=op.f('uq_students_bed_id')),
    sa.UniqueConstraint('user_id', name=op.f('uq_students_user_id'))
    )
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_students_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_students_current_status'), ['current_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_students_full_name'), ['full_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_students_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_students_school_name'), ['school_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_students_student_class'), ['student_class'], unique=False)
        batch_op.create_index(batch_op.f('ix_students_student_code'), ['student_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_students_verification_status'), ['verification_status'], unique=False)

    op.create_table('academic_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=80), nullable=False),
    sa.Column('exam_name', sa.String(length=120), nullable=False),
    sa.Column('exam_type', sa.String(length=60), nullable=True),
    sa.Column('marks_obtained', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('max_marks', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('grade', sa.String(length=5), nullable=True),
    sa.Column('teacher_remark', sa.Text(), nullable=True),
    sa.Column('exam_date', sa.Date(), nullable=False),
    sa.Column('recorded_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('marks_obtained >= 0', name=op.f('ck_academic_progress_marks_not_negative')),
    sa.CheckConstraint('max_marks > 0', name=op.f('ck_academic_progress_max_marks_positive')),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], name=op.f('fk_academic_progress_recorded_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_academic_progress_student_id_students'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_academic_progress'))
    )
    with op.batch_alter_table('academic_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_academic_progress_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_academic_progress_student_date', ['student_id', 'exam_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_academic_progress_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_academic_progress_subject'), ['subject'], unique=False)

    op.create_table('announcements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('audience', sa.Enum('ALL_PARENTS', 'ALL_STUDENTS', 'EVERYONE', 'SPECIFIC_STUDENT', 'SPECIFIC_CLASS', name='announcement_audience', native_enum=False), nullable=False),
    sa.Column('target_student_id', sa.Integer(), nullable=True),
    sa.Column('target_class', sa.String(length=40), nullable=True),
    sa.Column('attachment', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_announcements_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_student_id'], ['students.id'], name=op.f('fk_announcements_target_student_id_students'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_announcements'))
    )
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_announcements_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_announcements_is_active'), ['is_active'], unique=False)

    op.create_table('attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('session', sa.Enum('MORNING', 'EVENING', 'NIGHT', name='attendance_session', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('PRESENT', 'ABSENT', 'LEAVE', 'LATE', name='attendance_status', native_enum=False), nullable=False),
    sa.Column('marked_at', sa.DateTime(), nullable=False),
    sa.Column('marked_by_id', sa.Integer(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['marked_by_id'], ['users.id'], name=op.f('fk_attendance_marked_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_attendance_student_id_students'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attendance')),
    sa.UniqueConstraint('student_id', 'date', 'session', name='uq_attendance_student_id_date_session')
    )
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendance_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_date'), ['date'], unique=False)
        batch_op.create_index('ix_attendance_date_status', ['date', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_student_id'), ['student_id'], unique=False)

    op.create_table('daily_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('activity_type', sa.Enum('WAKE_UP', 'BREAKFAST', 'LEFT_FOR_SCHOOL', 'RETURNED_FROM_SCHOOL', 'LUNCH', 'STUDY', 'OUTDOOR_ACTIVITY', 'EVENING_SNACK', 'DINNER', 'PRAYER', 'LIGHTS_OUT', 'OTHER', name='activity_type', native_enum=False), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('scheduled_time', sa.Time(), nullable=True),
    sa.Column('activity_time', sa.Time(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('confirmed_by_student', sa.Boolean(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('recorded_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], name=op.f('fk_daily_activities_recorded_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_daily_activities_student_id_students'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_activities'))
    )
    with op.batch_alter_table('daily_activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_activities_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_activities_date'), ['date'], unique=False)
        batch_op.create_index('ix_daily_activities_student_date', ['student_id', 'date'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_activities_student_id'), ['student_id'], unique=False)

    op.create_table('emergency_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.Enum('MEDICAL_EMERGENCY', 'HOSTEL_EMERGENCY', 'SCHOOL_EMERGENCY', 'NATURAL_DISASTER', 'IMPORTANT_ANNOUNCEMENT', name='emergency_alert_type', native_enum=False), nullable=False),
    sa.Column('audience', sa.Enum('SINGLE_PARENT', 'SELECTED_PARENTS', 'ALL_PARENTS', name='emergency_audience', native_enum=False), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_emergency_alerts_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_emergency_alerts_student_id_students'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_emergency_alerts'))
    )
    with op.batch_alter_table('emergency_alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_emergency_alerts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_emergency_alerts_is_active'), ['is_active'], unique=False)

    op.create_table('health_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('HEALTHY', 'FEELING_UNWELL', 'SICK', 'MEDICAL_OBSERVATION', 'HOSPITALIZED', name='health_status', native_enum=False), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='health_severity', native_enum=False), nullable=False),
    sa.Column('symptoms', sa.Text(), nullable=True),
    sa.Column('temperature', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('medicine_given', sa.Text(), nullable=True),
    sa.Column('doctor_visited', sa.Boolean(), nullable=False),
    sa.Column('doctor_name', sa.String(length=150), nullable=True),
    sa.Column('hospital_visit', sa.Boolean(), nullable=False),
    sa.Column('hospital_name', sa.String(length=150), nullable=True),
    sa.Column('medical_remarks', sa.Text(), nullable=True),
    sa.Column('recovery_status', sa.Enum('ONGOING', 'RECOVERING', 'RECOVERED', name='health_recovery_status', native_enum=False), nullable=False),
    sa.Column('recovered_at', sa.DateTime(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('recorded_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], name=op.f('fk_health_records_recorded_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_health_records_student_id_students'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_health_records'))
    )
    with op.batch_alter_table('health_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_health_records_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_health_records_recorded_at'), ['recorded_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_health_records_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_health_records_student_id'), ['student_id'], unique=False)
        batch_op.create_index('ix_health_records_student_recorded', ['student_id', 'recorded_at'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('HEALTH_ALERT', 'ATTENDANCE_ALERT', 'SCHOOL_STATUS', 'PROGRESS_UPDATE', 'MEAL_UPDATE', 'ANNOUNCEMENT', 'SUGGESTION_REPLY', 'ACCOUNT_VERIFICATION', 'EMERGENCY_ALERT', 'ACTIVITY_UPDATE', 'GENERAL', name='notification_type', native_enum=False), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'NORMAL', 'HIGH', 'URGENT', name='notification_priority', native_enum=False), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('link', sa.String(length=255), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_notifications_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_notifications_student_id_students'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_notifications_user_read', ['user_id', 'is_read'], unique=False)

    op.create_table('progress_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('period_month', sa.Integer(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('recorded_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('period_month >= 1 AND period_month <= 12', name=op.f('ck_progress_records_month_range')),
    sa.CheckConstraint('score >= 0 AND score <= 100', name=op.f('ck_progress_records_score_range')),
    sa.ForeignKeyConstraint(['category_id'], ['progress_categories.id'], name=op.f('fk_progress_records_category_id_progress_categories'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], name=op.f('fk_progress_records_recorded_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_progress_records_student_id_students'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_progress_records')),
    sa.UniqueConstraint('student_id', 'category_id', 'period_year', 'period_month', name='uq_progress_records_student_id_category')
    )
    with op.batch_alter_table('progress_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_progress_records_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_progress_records_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_progress_records_period_year'), ['period_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_progress_records_student_id'), ['student_id'], unique=False)

    op.create_table('school_attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('WENT_TO_SCHOOL', 'DID_NOT_GO', 'ON_LEAVE', 'SCHOOL_HOLIDAY', 'RETURNED_FROM_SCHOOL', name='school_attendance_status', native_enum=False), nullable=False),
    sa.Column('departure_time', sa.Time(), nullable=True),
    sa.Column('expected_return_time', sa.Time(), nullable=True),
    sa.Column('actual_return_time', sa.Time(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('recorded_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], name=op.f('fk_school_attendance_recorded_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_school_attendance_student_id_students'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_school_attendance')),
    sa.UniqueConstraint('student_id', 'date', name='uq_school_attendance_student_id_date')
    )
    with op.batch_alter_table('school_attendance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_school_attendance_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_school_attendance_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_school_attendance_student_id'), ['student_id'], unique=False)

    op.create_table('student_parent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('relationship_type', sa.String(length=50), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.id'], name=op.f('fk_student_parent_parent_id_parents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_student_parent_student_id_students'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student_parent')),
    sa.UniqueConstraint('student_id', 'parent_id', name='uq_student_parent_student_id')
    )
    with op.batch_alter_table('student_parent', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_parent_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_parent_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_parent_student_id'), ['student_id'], unique=False)

    op.create_table('student_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('IN_HOSTEL', 'AT_SCHOOL', 'OUTSIDE_WITH_PERMISSION', 'ON_LEAVE', 'MEDICAL_FACILITY', 'RETURNED_TO_HOSTEL', name='status_history_status', native_enum=False), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_student_status_history_student_id_students'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_student_status_history_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student_status_history'))
    )
    with op.batch_alter_table('student_status_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_status_history_changed_at'), ['changed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_status_history_student_id'), ['student_id'], unique=False)

    op.create_table('suggestions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.Enum('PARENT', 'STUDENT', name='suggestion_source', native_enum=False), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(length=180), nullable=False),
    sa.Column('category', sa.Enum('FOOD', 'STUDY', 'HEALTH', 'ROOM', 'DISCIPLINE', 'ACTIVITIES', 'SCHOOL', 'GENERAL', 'OTHER', name='suggestion_category', native_enum=False), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('attachment', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'UNDER_REVIEW', 'IN_PROGRESS', 'RESOLVED', name='suggestion_status', native_enum=False), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_suggestions_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.id'], name=op.f('fk_suggestions_parent_id_parents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_suggestions_student_id_students'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_suggestions'))
    )
    with op.batch_alter_table('suggestions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_suggestions_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_suggestions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_suggestions_created_by_id'), ['created_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_suggestions_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_suggestions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_suggestions_student_id'), ['student_id'], unique=False)

    op.create_table('emergency_alert_recipients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['emergency_alerts.id'], name=op.f('fk_emergency_alert_recipients_alert_id_emergency_alerts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_emergency_alert_recipients_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_emergency_alert_recipients')),
    sa.UniqueConstraint('alert_id', 'user_id', name='uq_emergency_alert_recipients_alert_id')
    )
    with op.batch_alter_table('emergency_alert_recipients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_emergency_alert_recipients_alert_id'), ['alert_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_emergency_alert_recipients_user_id'), ['user_id'], unique=False)

    op.create_table('suggestion_replies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('suggestion_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_suggestion_replies_author_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['suggestion_id'], ['suggestions.id'], name=op.f('fk_suggestion_replies_suggestion_id_suggestions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_suggestion_replies'))
    )
    with op.batch_alter_table('suggestion_replies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_suggestion_replies_suggestion_id'), ['suggestion_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suggestion_replies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suggestion_replies_suggestion_id'))

    op.drop_table('suggestion_replies')
    with op.batch_alter_table('emergency_alert_recipients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_emergency_alert_recipients_user_id'))
        batch_op.drop_index(batch_op.f('ix_emergency_alert_recipients_alert_id'))

    op.drop_table('emergency_alert_recipients')
    with op.batch_alter_table('suggestions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suggestions_student_id'))
        batch_op.drop_index(batch_op.f('ix_suggestions_status'))
        batch_op.drop_index(batch_op.f('ix_suggestions_parent_id'))
        batch_op.drop_index(batch_op.f('ix_suggestions_created_by_id'))
        batch_op.drop_index(batch_op.f('ix_suggestions_created_at'))
        batch_op.drop_index(batch_op.f('ix_suggestions_category'))

    op.drop_table('suggestions')
    with op.batch_alter_table('student_status_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_status_history_student_id'))
        batch_op.drop_index(batch_op.f('ix_student_status_history_changed_at'))

    op.drop_table('student_status_history')
    with op.batch_alter_table('student_parent', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_parent_student_id'))
        batch_op.drop_index(batch_op.f('ix_student_parent_parent_id'))
        batch_op.drop_index(batch_op.f('ix_student_parent_created_at'))

    op.drop_table('student_parent')
    with op.batch_alter_table('school_attendance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_school_attendance_student_id'))
        batch_op.drop_index(batch_op.f('ix_school_attendance_date'))
        batch_op.drop_index(batch_op.f('ix_school_attendance_created_at'))

    op.drop_table('school_attendance')
    with op.batch_alter_table('progress_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_progress_records_student_id'))
        batch_op.drop_index(batch_op.f('ix_progress_records_period_year'))
        batch_op.drop_index(batch_op.f('ix_progress_records_created_at'))
        batch_op.drop_index(batch_op.f('ix_progress_records_category_id'))

    op.drop_table('progress_records')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index('ix_notifications_user_read')
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_type'))
        batch_op.drop_index(batch_op.f('ix_notifications_student_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_is_read'))
        batch_op.drop_index(batch_op.f('ix_notifications_created_at'))

    op.drop_table('notifications')
    with op.batch_alter_table('health_records', schema=None) as batch_op:
        batch_op.drop_index('ix_health_records_student_recorded')
        batch_op.drop_index(batch_op.f('ix_health_records_student_id'))
        batch_op.drop_index(batch_op.f('ix_health_records_status'))
        batch_op.drop_index(batch_op.f('ix_health_records_recorded_at'))
        batch_op.drop_index(batch_op.f('ix_health_records_created_at'))

    op.drop_table('health_records')
    with op.batch_alter_table('emergency_alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_emergency_alerts_is_active'))
        batch_op.drop_index(batch_op.f('ix_emergency_alerts_created_at'))

    op.drop_table('emergency_alerts')
    with op.batch_alter_table('daily_activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_activities_student_id'))
        batch_op.drop_index('ix_daily_activities_student_date')
        batch_op.drop_index(batch_op.f('ix_daily_activities_date'))
        batch_op.drop_index(batch_op.f('ix_daily_activities_created_at'))

    op.drop_table('daily_activities')
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_student_id'))
        batch_op.drop_index('ix_attendance_date_status')
        batch_op.drop_index(batch_op.f('ix_attendance_date'))
        batch_op.drop_index(batch_op.f('ix_attendance_created_at'))

    op.drop_table('attendance')
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_announcements_is_active'))
        batch_op.drop_index(batch_op.f('ix_announcements_created_at'))

    op.drop_table('announcements')
    with op.batch_alter_table('academic_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_academic_progress_subject'))
        batch_op.drop_index(batch_op.f('ix_academic_progress_student_id'))
        batch_op.drop_index('ix_academic_progress_student_date')
        batch_op.drop_index(batch_op.f('ix_academic_progress_created_at'))

    op.drop_table('academic_progress')
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_students_verification_status'))
        batch_op.drop_index(batch_op.f('ix_students_student_code'))
        batch_op.drop_index(batch_op.f('ix_students_student_class'))
        batch_op.drop_index(batch_op.f('ix_students_school_name'))
        batch_op.drop_index(batch_op.f('ix_students_is_active'))
        batch_op.drop_index(batch_op.f('ix_students_full_name'))
        batch_op.drop_index(batch_op.f('ix_students_current_status'))
        batch_op.drop_index(batch_op.f('ix_students_created_at'))

    op.drop_table('students')
    with op.batch_alter_table('meal_photos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meal_photos_meal_id'))

    op.drop_table('meal_photos')
    with op.batch_alter_table('token_blocklist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_token_blocklist_user_id'))
        batch_op.drop_index(batch_op.f('ix_token_blocklist_jti'))

    op.drop_table('token_blocklist')
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_token_hash'))

    op.drop_table('password_reset_tokens')
    with op.batch_alter_table('parents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parents_verification_status'))
        batch_op.drop_index(batch_op.f('ix_parents_created_at'))
        batch_op.drop_index(batch_op.f('ix_parents_claimed_student_code'))

    op.drop_table('parents')
    with op.batch_alter_table('meals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meals_date'))
        batch_op.drop_index(batch_op.f('ix_meals_created_at'))

    op.drop_table('meals')
    with op.batch_alter_table('beds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_beds_room_id'))
        batch_op.drop_index(batch_op.f('ix_beds_created_at'))

    op.drop_table('beds')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_type'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_admin_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('admin_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_profiles_created_at'))

    op.drop_table('admin_profiles')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_phone'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_created_at'))
        batch_op.drop_index(batch_op.f('ix_users_account_status'))

    op.drop_table('users')
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rooms_room_number'))
        batch_op.drop_index(batch_op.f('ix_rooms_created_at'))
        batch_op.drop_index(batch_op.f('ix_rooms_building'))

    op.drop_table('rooms')
    with op.batch_alter_table('progress_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_progress_categories_slug'))
        batch_op.drop_index(batch_op.f('ix_progress_categories_created_at'))

    op.drop_table('progress_categories')
    # ### end Alembic commands ###
